### ISSUE TITLE
Tidal with legit PREMIUM account goes in a loop; configuration problem?

### ISSUE THREAD

**Issue by Piggoz** [Dniel97/orpheusdl-tidal#29] opened 2023-02-09 16:34 UTC
`**Describe` the bug**
 Hello, I have this problem with a valid, legit Tidal Premium account when I try to download something.

` TIDAL: Account does not have a HiFi (Plus) subscription, detected subscription: PREMIUM
 Do you want to create a new session? [Y/n]: y
 TIDAL: Recreating a TV session
Opening https://link.tidal.com/OFZQX, log in or sign up to TIDAL.
Checking link
Successfully linked!
 TIDAL: Account does not have a HiFi (Plus) subscription, detected subscription: PREMIUM
 Do you want to create a new session? [Y/n]: n
 Exiting...`

If I do choose to create a new session, it goes in a loop where always ask me for a new session; If I say No, it end the program and do not download.

**To Reproduce**
 1. login with a legit PREMIUM account and try to download something
 2. reply Y to create a new session and it will ask for it in a loop; choose No and it will end the session and no download.
 

  **Expected behavior**
 To login like it do and to download without complaining my subscription is PREMIUM.

 
  **Desktop (please complete the following information):**
  - OS: windows 10 pro
  - Python version 3.11

 ![image](https://user-images.githubusercontent.com/45820275/217877536-4f8ad54b-8446-4e86-a7bf-f78c368f7c0b.png)

**Comment by Dniel97** [comment] 2023-02-09 18:07
Do you have a Premium or a HiFi subscription? Because the premium subscription only supports AAC and is not supported by OrpheusDL. Therefore does your subscription support lossless streaming?

**Comment by Piggoz** [comment] 2023-02-09 21:40
Hi and thank you for your reply. I do have a HiFi (Individual) subscription. I listen from the app in hifi. I do not have access to MQA files, I can stream Flac, so I should download them too. Few years ago I used with a similar subscription a tool called Tidal-DL to download from Tidal with a legit account and it worked fine. If memory serve me well, the mechanism was the same: to register the tool with Tidal (like with this Orpheus-DL), then at the time it worked. Now I still have this message here when I try to download. Is it something we could fix in the settings? I don't know what to do.

!(https://user-images.githubusercontent.com/45820275/217945153-ac6d1d7b-d9dc-4179-acad-b0da95810b4f.jpg)

**Comment by Piggoz** [comment] 2023-02-09 22:13
That tool I said in my previous report STILL works! I downloaded the latest version, configured and it perfectly fine download flacs from my account! The problem with your tool is the account type! On Tidal-dl config tab, I had to choose: "2     | True | Android TV   | Normal/High/HiFi(No Master)". Something like this seems not available in OrpheusDL-tidal. Your tool seems it want me to login in the plus account type, the one with MQA, and this is not available in my simple hIFI subscription. I hope it is just my fault in the OrpheusDL config file and this can be fixed, becouse I really like OrpheusDL (long time user with my legit Qobux account and it is so fast and reliable, better than any other tool) and I really will enjoy to use it also with Tidal. Thank you.

**Comment by Dniel97** [comment] 2023-02-10 11:22
I never tried a "PREMIUM" or now just HiFi account at all so there is no guarantee it will work as intended, because many features rely on a HiFi Plus subscription, you can disable the subscription check globally in OrpheusDL by setting `disable_subscription_checks` to `True`.

**Comment by Piggoz** [comment] 2023-02-10 12:50
With this settings, it works but... it just download m4a files :-( Any other settings to tell the program to download flacs, if they exists and you can help? Too bad I need to have three different programs to download flacs from Qobuz (perfectly fine with OrpheusDL), Tidal (Tidal-DL now also with graphical interface) and the not developed anymore Deemix for Deezer? :-(

**Comment by Dniel97** [comment] 2023-02-10 12:52
Because you didn't read the error message, make sure you have ffmpeg installed. It's most likely still a flag audio track inside a MPEG-4 container.

**Comment by Piggoz** [comment] 2023-02-10 12:54
FFmpeg globally installed in the system? Or it do exist a FFmpeg plugin for OrpheusDL? I do have FFmpeg in the system via CodecPacks.

**Comment by Dniel97** [comment] 2023-02-10 13:04
Open up CMD and type `ffmpeg` see if it works or if it shows "command not found". I recommend adding a mobile session too and also install ffmpeg properly like here: [https://www.wikihow.com/Install-FFmpeg-on-Windows](https://www.wikihow.com/Install-FFmpeg-on-Windows).

**Comment by Piggoz** [comment] 2023-02-10 14:13
Thank you for your support. Case closed. Everything seems fine now with FFmpeg in the path. IMHO, you should specify this instructions for people with the simple hifi (ex premium) account (I think the majority of the users, 5 euro less for month). Just curious: why I should add a mobile session too, technically speaking? What advantages could have? I admit I disable it from the settings file. If needed I could re-enabled it.

**Comment by Dniel97** [comment] 2023-02-10 15:17
If you use a mobile session you don't need to setup ffmpeg and you get faster download speeds.

**Comment by Piggoz** [comment] 2023-02-10 16:06
hey thank you again! This really makes the difference and now the speed is the same of the Qobuz plugin. And no FFMpeg bloat in the path. Then just curious about this problem: file tags are there also using your plugin, every player can correctly see it but... Windows Explorer!!! This doesn't happen with Tidal-dl: the tags produced by it are there ALSO for Windows Explorer, as you can see comparing the two pix I include in this comment. Why this? And how can fix this too in the OrpheusDL-tidal plugin? Thanx you again! 
![tidaldl](https://user-images.githubusercontent.com/45820275/218139082-3bb61481-4d40-4481-9693-5a46f11cbc38.png)
![orpheusDL-tidal](https://user-images.githubusercontent.com/45820275/218139119-e6345534-1de4-4c98-949a-cb537850b8d8.png)

**Comment by Dniel97** [comment] 2023-02-11 12:07
Not sure why that's the case because you don't show the file extension or a MediaInfo of two identical tracks.

**Comment by Piggoz** [comment] 2023-02-11 14:59
Here it is! On the left we have OrpheusDL-tidal same file properties. On the right, same file downloaded with the revamped Tidal-dl. Way too much infos in OrpheusDL-tidal tags!!! I bet that is the problem of the wrong visualization in Windows Explorer, even if shouldn't. And also, in the properties of the file, we can see REPLAY GAIN applied to the file! I deeply hate replay gain and I don't want it. So how can i get less info from the Tidal server and how I can disable horrid replay gain? :-) Thank you in advance.
![tag](https://user-images.githubusercontent.com/45820275/218265514-773bf7aa-81e3-4218-ac83-a84a97eca07b.png)
![prop](https://user-images.githubusercontent.com/45820275/218265521-44d0f69d-8bad-4811-95d7-3d63b6bb8581.png)

**Comment by Dniel97** [comment] 2023-02-11 15:49
You can ALWAYS disable ReplayGain in your player of choice, it doesn't harm adding a couple of bytes to a file which metadata gets already fetched in the same request so I'm closing this issue now because of offtopic.

**Closed by Dniel97** 2023-02-11 15:49 UTC
Labels: bug
